# Generated by Django 4.2.3 on 2023-11-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_comment_comment_remove_comment_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
